<?php
/**
* @file
* Module file for mycorp_greeting
*/

/**
 * Implements hook_node_info()
 */
function mycorp_greeting_node_info() {
    return array(
        'greetings' => array(
            'name' => t('Greeting'),
            'base' => 'greetings',
            'description' => t('You can set new Greeting here'),
            'has_title' => TRUE,
            'title_label' => t('Greeting title')
         )
    );
}

/**
 * Implement hook_form()
 */
function greetings_form($node, $form_state) {
    return node_content_form($node, $form_state);
}
